services:
  api:
    container_name: evolution_api
    build:
      context: .
      dockerfile: Dockerfile.master
    restart: always
    depends_on:
      redis:
        condition: service_started
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env.production
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    dns:
      - 8.8.8.8
      - 1.1.1.1

  redis:
    image: redis:alpine
    networks:
      - evolution-net
    container_name: redis
    command: redis-server --appendonly yes --requirepass 74wzfbpv
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

volumes:
  evolution_instances:
  evolution_redis:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge