
app = 'zaia-whatsapp-gateway-prod'
primary_region = 'atl'

[build]
  dockerfile = '../../Dockerfile.master'

[env]
  DEBUG = '1'
  NODE_ENV = 'production'
  WHATSAPP_API_HOSTNAME = 'zaia-whatsapp-gateway-prod.internal'
  WHATSAPP_API_PORT = '3006'
  WHATSAPP_DEFAULT_ENGINE = 'NOWEB'
  WHATSAPP_RESTART_ALL_SESSIONS = 'True'
  WHATSAPP_SWAGGER_USERNAME = 'admin'
  WAHA_DASHBOARD_ENABLED = 'True'
  WAHA_DASHBOARD_USERNAME = 'admin'
  
[[mounts]]
  source = 'sessions_data'
  destination = '/app/.sessions'
  snapshot_retention = 15
  auto_extend_size_threshold = 99
  auto_extend_size_increment = '5GB'
  auto_extend_size_limit = '100GB'
  initial_size='5GB'

[http_service]
  internal_port = 3006
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 1
