
app = 'zaia-evolution-api-whatsapp-gateway-2-prod'
primary_region = 'gru'

[build]
  dockerfile = '../../Dockerfile.master'

[[mounts]]
  source = 'sessions_data'
  destination = '/app/.sessions'
  snapshot_retention = 15
  auto_extend_size_threshold = 99
  auto_extend_size_increment = '5GB'
  auto_extend_size_limit = '100GB'
  initial_size='5GB'

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 1
