name: CI/CD
on:
  push:
    branches:
      - release
jobs:
  deploy:
    name: Staging Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fly Setup
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: |
          flyctl deploy --wg=false --no-cache --local-only --config ./fly.io/staging/values.toml --access-token='${{ secrets.FLY_API_TOKEN_STAGING }}'
          flyctl deploy --wg=false --no-cache --local-only --config ./fly.io/staging/values-2.toml --access-token='${{ secrets.FLY_API_TOKEN_2_STAGING }}'